from __future__ import annotations

from PySide6.QtCore import QEvent, QModelIndex, QUrl, Qt, QThread, QTimer, Signal
from PySide6.QtGui import QFont, QImage, QPixmap, QIcon, QKeySequence, QShortcut
from PySide6.QtMultimedia import QAudioOutput, QMediaPlayer
from PySide6.QtMultimediaWidgets import QVideoWidget
from PySide6.QtWidgets import (
    QApplication,
    QCheckBox,
    QComboBox,
    QDialog,
    QDialogButtonBox,
    QDoubleSpinBox,
    QFileDialog,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QMainWindow,
    QMessageBox,
    QMenu,
    QPlainTextEdit,
    QPushButton,
    QProgressBar,
    QRadioButton,
    QScrollArea,
    QSizePolicy,
    QSpinBox,
    QSlider,
    QStatusBar,
    QStackedWidget,
    QStyle,
    QTableWidget,
    QTableWidgetItem,
    QAbstractItemView,
    QTabWidget,
    QTextEdit,
    QToolTip,
    QButtonGroup,
    QVBoxLayout,
    QWidget,
    QWidgetAction,
)
