from __future__ import annotations

from pathlib import Path

from src.services.settings.model import (
    AiPrelabelSettings,
    AnnotationSettings,
    AppSettings,
    ConversionSettings,
    DatasetSettings,
    FeatureSettings,
    ImageResizeSettings,
    LineToObbSettings,
    ModelExportSettings,
    PathSettings,
    ProjectSettings,
    RenameSettings,
    SamAssistSettings,
    SplitRatios,
    TaskSettings,
    TrainingSettings,
    UiSettings,
    ValidationSettings,
)
from src.shared.paths import ROOT


def build_default_settings(project_root: Path = ROOT) -> AppSettings:
    project_root = Path(project_root)
    data_root = project_root / "data"
    models_root = data_root / "models"
    return AppSettings(
        project=ProjectSettings(root=str(project_root)),
        paths=PathSettings(
            images_dir=str(project_root / "images"),
            annotations_dir=str(project_root / "images"),
            labels_dir=str(project_root / "labels"),
            dataset_dir=str(data_root),
            models_dir=str(models_root),
            result_dir=str(project_root / "result"),
        ),
        task=TaskSettings(mode="detect"),
        dataset=DatasetSettings(
            class_names=[],
            split_ratios=SplitRatios(train=0.8, val=0.2, test=0.0),
            line_to_obb=LineToObbSettings(enabled=True, half_width=10.0),
            random_seed=42,
        ),
        image_resize=ImageResizeSettings(
            source_dir=str(project_root / "images"),
            long_edge=960,
            canvas_size=960,
            background="white",
            output_dir=str(project_root / "images_resized"),
            backup_dir=str(project_root / "images_backup"),
            backup_enabled=False,
        ),
        training=TrainingSettings(
            model_yaml="",
            base_model="yolo11s.pt",
            pretrained=str(models_root / "yolo11s.pt"),
            data=str(data_root / "data.yaml"),
            project=str(project_root / "result"),
            export_format="onnx",
            lr=0.001,
            epochs=500,
            patience=100,
            workers=2,
            batch=16,
            imgsz=640,
            device="0",
            mosaic=1.0,
            fliplr=0.5,
            flipud=0.0,
            mixup=0.0,
            scale=0.5,
            translate=0.1,
            degrees=0.0,
            hsv_h=0.015,
            hsv_s=0.7,
            hsv_v=0.4,
            optimizer="auto",
        ),
        validation=ValidationSettings(
            model_path="",
            source_mode="图片检测",
            source_path="",
            source_selection="全部图片",
            data=str(data_root / "data.yaml"),
            source_scope="全部图片",
            camera_index=0,
            confidence=0.25,
            iou=0.45,
            imgsz=640,
            save_dir=str(project_root / "result" / "gui_val"),
        ),
        conversion=ConversionSettings(
            use_labelme=True,
            backup_yolo_files=False,
            class_name_mappings={},
        ),
        model_export=ModelExportSettings(
            model_path="",
            output_dir=str(project_root / "data" / "models" / "model_exports"),
            format="onnx",
            imgsz=640,
            simplify=True,
        ),
        annotation=AnnotationSettings(
            auto_save=True,
            auto_convert_yolo=False,
            show_yolo_save_in_context_menu=False,
            show_annotation_names=False,
            show_canvas_status=True,
            continuous_draw=False,
            quick_draw=False,
            line_expand_enabled=False,
            line_expand_pixels=10,
            optimize_mirror_edit=False,
            ai_prelabel=AiPrelabelSettings(
                model_path="",
                confidence=0.50,
                iou=0.45,
                sam3_confidence=0.50,
                sam3_dedup_iou=0.80,
                sam3_output_shape="rect",
                sam3_prompts={},
                sam3_enabled_classes=[],
                sam3_min_area=4,
                sam3_polygon_simplify_ratio=0.002,
                range_mode="当前图片",
                process_mode="追加",
                custom_selected_images=[],
            ),
            sam_assist=SamAssistSettings(
                model_path="",
                multimask_output=False,
                minimum_score=0.0,
                minimum_area=4,
                polygon_simplification_ratio=0.002,
            ),
        ),
        rename=RenameSettings(
            prefix="A",
            start_index=1,
            padding=1,
            include_labelme=False,
            include_yolo=False,
        ),
        ui=UiSettings(last_page="home", window_width=1100, window_height=770),
        features=FeatureSettings(
            distribution_multi_class_mode=False,
            custom_command_dialog=True,
            show_help_icons=True,
            show_last_training_models=False,
            resize_output_mode="输出到新文件夹",
        ),
    )


__all__ = ["build_default_settings"]
